In [1]:
import numpy as np

In [12]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])

Сложение

In [13]:
print(a + b)

[7 7 7]


Вычитание

In [15]:
print(a - b)

[-5 -3 -1]


Покоординатное умножение

In [16]:
print(a * b)

[ 6 10 12]


Умножение вектора на число

In [17]:
print(a * 7)

[ 7 14 21]


Скалярное произведение a и b

In [18]:
print(np.dot(a, b))

28


#### 5.2

Вычислите определитель

\begin{equation}
  \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 0 & 6 \\
    7 & 8 & 9
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}

\begin{align}
\Delta1,1 = 0 * 9 - 8 * 6 = -48 \\
\Delta2,1 = 2 * 9 - 3 * 8 = -6 \\
\Delta3,1 = 2 * 6 - 3 * 0 = 12 \\
\Delta = 1 - (-48) - 4 * (-6) + 7 * 12 = -48 + 24 + 84 = 60
\end{align}