## Задание 5.1

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])

Сложение

In [3]:
print(a + b)

[7 7 7]


Вычитание

In [4]:
print(a - b)

[-5 -3 -1]


Покоординатное умножение

In [5]:
print(a * b)

[ 6 10 12]


Умножение вектора на число

In [6]:
print(a * 7)

[ 7 14 21]


Скалярное произведение a и b

In [7]:
print(np.dot(a, b))

28


## Задание 5.2

Вычислите определитель

$
\begin{equation}
  \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 0 & 6 \\
    7 & 8 & 9
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

$
\Delta1,1 = 0 * 9 - 8 * 6 = -48 \\
\Delta2,1 = 2 * 9 - 3 * 8 = -6 \\
\Delta3,1 = 2 * 6 - 3 * 0 = 12 \\
\Delta = 1 - (-48) - 4 * (-6) + 7 * 12 = -48 + 24 + 84 = 60
$

## Задание 5.3

##### Часть 1

Вычислите матрицу, обратную данной:

$
\begin{equation}
  \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 0 & 6 \\
    7 & 8 & 9
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

Определитель матрицы

$
\Delta_{1,1} = 0 * 9 - 8 * 6 = -48 \\
\Delta_{2,1} = 2 * 9 - 3 * 8 = -6 \\
\Delta_{3,1} = 2 * 6 - 3 * 0 = 12 \\
\Delta = 1 - (-48) - 4 * (-6) + 7 * 12 = -48 + 24 + 84 = 60
$

Найдем алгебраические дополнения:

$
A_{1,1}  = (-1)^2 * (0 * 9 - 6 * 8) = -48 \\
A_{1,2}  = (-1)^3 * (4 * 9 - 6 * 7) = 4 \\
A_{1,3}  = (-1)^4 * (4 * 8 - 0 * 7) = 32 \\
A_{2,1}  = (-1)^3 * (4 * 9 - 6 * 7) = 6 \\
A_{2,2}  = (-1)^4 * (1 * 9 - 3 * 7) = -12 \\
A_{2,3}  = (-1)^5 * (1 * 6 - 3 * 4) = 6 \\
A_{3,1}  = (-1)^4 * (2 * 6 - 3 * 0) = 12 \\
A_{3,2}  = (-1)^5 * (1 * 6 - 3 * 4) = 6 \\
A_{3,3}  = (-1)^6 * (1 * 0 - 2 * 4) = -8
$

C = $
\begin{equation}
  \begin{bmatrix}
    -48 & 6 & 12 \\
    6 & -12 & 6 \\
    32 & 6 & -8
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

Обратная матрица

$
A^{-1} = \frac{1}{60} * \begin{equation}
  \begin{bmatrix}
    -48 & 6 & 12 \\
    6 & -12 & 6 \\
    32 & 6 & -8
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

$
A^{-1} = \begin{equation}
  \begin{bmatrix}
    -0,8 & 0,1 & 0,2 \\
    0,1 & -0,2 & 0,1 \\
    0,533 & 0,1 & -0,133
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

##### Проверим через Numpy

In [8]:
import numpy as np

In [9]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [10]:
np.linalg.inv(A)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

#### Часть 2

Приведите пример матрицы 4х4, ранг которой равен 1.

A = $
\begin{equation}
  \begin{bmatrix}
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

***проверка***

In [11]:
A = np.array([[1,1,1,1], [1,1,1,1], [1,1,1,1], [1,1,1,1]])

In [12]:
print(np.linalg.matrix_rank(A))

1


## Задание 5.4.

Вычислите скалярное произведение двух векторов: (1, 5)  и  (2, 8)

$
\vec{\mathbf{a}} \vec{\mathbf{b}} = 1 * 2 + 5 * 8 = 2 + 40 = 42
$

***Проверка на numpy***

In [13]:
a = np.array([1, 5])
b = np.array([2, 8])
print(np.dot(a, b))

42


## Задание 5.5.

Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

$
a = (1, 5, 0) \\
b = (2, 8, 7) \\
c = (7, 1.5, 3)
$

$
A = \begin{equation}
  \begin{bmatrix}
    1 & 5 & 0 \\
    2 & 8 & 7 \\
    7 & 1.5 & 3
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}
$

B = (1 * 8 * 3) - (1 * 7 * 1.5) - (2 * 5 * 3) + ( 2 * 0 * 1.5) + (7 * 5 * 7) - (7 * 0 * 8) = 24 - 10.5 - 30 + 245 = 228.5